---
- name: Install jenkins
  hosts: localhost
  become: yes
  become_user: root

  tasks:
  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest

  - name: Install fontconfig
    shell: apt install fontconfig -y    

  - name: Install java
    shell: apt install fontconfig openjdk-17-jre -y  


   
  - name: Add Jenkins repository key
    apt_key:
     url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
     state: present

  - name: Add Jenkins repository
    apt_repository:
      repo: https://pkg.jenkins.io/debian-stable binary/
      state: present

    # Step 3: Update apt cache
  - name: Update apt cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

    # Step 4: Install Jenkins
  - name: Install Jenkins
    apt:
      name: jenkins
      state: present

    # Step 5: Start and enable Jenkins service
  - name: Start Jenkins service
    systemd:
      name: jenkins
      enabled: yes
      state: started
